config/routes.rb
Rails.application.routes.draw do

  get 'about', to: 'static_pages#about', as: 'about'

  post 'grading/start/:quiz_id', to: 'grading#start', as: 'start_grading'

  post 'grading/complete/:quiz_id', to: 'grading#complete',
       as: 'complete_grading'

  get 'grading/:quiz_id/:question_number', to: 'grading#question',
      as: 'question_grading'

  post 'grading/:quiz_id/:question_number', to: 'grading#save_grading'

  get 'grading/:quiz_id', to: 'grading#show', as: :grading

  resources :players

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :response_sheets, only: [:create]

  resources :responses

  resources :questions, only: [:show, :update] do
    member do
      get "edit_question"
      get "edit_answer"
    end
  end

  resources :quizzes

  post 'start_quiz/:id', to: 'quizzes#start_quiz', as: 'start_quiz'
  get 'finalize/:id', to: 'quizzes#finalize', as: 'finalize'

  root 'quizzes#home_page'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz, counter_cache: true
  has_many :responses, autosave: true

  validates :number, numericality: { only_integer: true }
  validates :question_text, :answer, presence: true, on: :finalize

  BLANK_STRING = "*~*~* BLANK STRING *~*~*"

  def responses_graded_count
    Rails.cache.fetch [self, "responses_graded_count"] do
      responses.graded.size
    end
  end

  def responses_moneyed_count
    Rails.cache.fetch [self, "responses_moneyed_count"] do
      responses.where(money: true).size
    end
  end

  def responses_correct_count
    Rails.cache.fetch [self, "responses_correct_count"] do
      responses.correct.size
    end
  end

  def percent_graded
    if self.responses_count != 0
      ( self.responses_graded_count.to_f / self.responses_count.to_f ) * 100
    else
      0.0
    end
  end

  def percent_moneyed
    if self.responses_count != 0
      ( self.responses_moneyed_count.to_f / self.responses_count.to_f ) * 100
    end
  end

  def percent_correct
    if self.responses_graded_count != 0
      ( self.responses_correct_count.to_f / self.responses_graded_count.to_f ) * 100
    end
  end

  def set_money_value!
    self.update(money_value: [100 - self.percent_correct.floor, 99].min)
  end

  def update_question(new_text)
    unless self.edited_text || new_text.blank? || new_text == self.question_text
      self.edited_text = new_text
      self.question_edited_at = Time.now
      self.save
    end
  end

  def update_answer(new_text)
    unless self.edited_answer || new_text.blank? || new_text == self.answer
      self.edited_answer = new_text
      self.answer_edited_at = Time.now
      self.save
    end
  end

  def responses_hash
    resp_hash = {}
    self.responses.each do |response|
      processed_response = Question.prepare_string(response.response_text)

      if resp_hash.has_key? processed_response
        resp_hash[processed_response][:count] += 1
      else
        resp_hash[processed_response] =
          {correct: response.correct, count: 1}
      end
    end
    resp_hash
  end

  def self.prepare_string(raw_string)
    if raw_string.blank?
      BLANK_STRING
    else
      raw_string.
        tr("[","(").
        tr("]",")").
        upcase
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_question!
  before_action :authenticate_user!, except: [:show]
  before_action :authorize_author!, except: [:show]
  before_action :only_use_active_quizzes!, except: [:show]

  def show
    if user_signed_in? && @quiz.author == current_user.player
      @can_edit = true
      @responses_hash = @question.responses_hash.sort
    end
    unless @quiz.complete? || @can_edit

      redirect_to quiz_path(@question.quiz),
        alert: "You cannot view that question summary right now"

    end
  end

  def edit_question
    if @question.question_edited_at
      redirect_to question_path(@quiz),
        alert: "You have already edited this question"
    end

  end

  def edit_answer
    if @question.answer_edited_at
      redirect_to question_path(@quiz),
        alert: "You have already edited this answer"
    end
  end

  def update
    if params[:edit_type] == "question"
      if @question.update_question(params[:question][:new_text])
        redirect_to question_path(@question)
      else
        render :edit_question
      end
    elsif params[:edit_type] == "answer"
      if @question.update_answer(params[:question][:new_answer])
        redirect_to question_path(@question)
      else
        render :edit_answer
      end
    else
      redirect_to quiz_path(@quiz), alert: "Invalid information"
    end
  end

  private

  def set_question!
    @question = Question.find(params[:id])
    @quiz = @question.quiz
  end

  def authorize_author!
    unless @quiz.author == current_user.player
      redirect_to quiz_path(@quiz),
        alert: "You cannot edit this answer"
    end
  end

  def only_use_active_quizzes!
    unless @quiz.opened
      redirect_to quiz_path(@quiz),
        alert: "You cannot view or edit individual questions unless the quiz is already opened"
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-0
            col-md-4 col-md-offset-0 col-lg-3 col-lg-offset-0
            col-full-height">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h2 class="panel-title">
        <% if @can_edit %>
          <%= link_to "Question #{question.number}",
                      question_path(question) %>
        <% else %>
          Question <%= question.number %>
        <% end %>
      </h2>
    </div>
    <div class="question-body">
      <p><%= sanitize current_question_text(question) %></p>
      <% if not(question.external_link.blank?) %>
        <p><%= link_to "Click for additional information",
                       url_with_protocol(question.external_link),
                       target: "_blank" %></p>
      <% end %>
    </div>
    <% if @response_sheet %>
      <% response = question.responses.
                    find_by_response_sheet_id(@response_sheet) %>
      <ul class="list-group">
        <li class="list-group-item">
          <p class="text-left">
            <strong>Your response:</strong>
          </p>
          <p class="text-center">
            <strong class="text-center"><%= response.response_text %></strong>
            <% if response.money %>
              <span class='glyphicon glyphicon-usd' aria-hidden='true'></span>
              <span class="sr-only">Moneyed</span>
            <% end %>
          </p>
        </li>
      </ul>
    <% end %>
    <div class="revealed-answer">
      <%= current_answer(question) %>
    </div>
  </div>
</div>
<div class="question-clearfix"></div>

app/views/questions/edit_answer.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= form_for(@question) do |f| %>
      <%= hidden_field_tag :edit_type, "answer" %>
      <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@question.errors.count, "error") %>
            prohibited this question from being edited:
          </h2>

          <ul>
            <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h1 class="page-header">
        Edit Answer
      </h1>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title">Question <%= @question.number %></h2>
        </div>
        <div class="question-body">
          <p><%= sanitize current_question_text(@question) %></p>
          <% if @question.question_edited_at %>
            <p>
              <strong>Original question:</strong>
              <%= sanitize @question.question_text %>
            </p>
          <% end %>


          <% if not(@question.external_link.blank?) %>
            <p><%= link_to "Click for additional information",
                           url_with_protocol(@question.external_link),
                           target: "_blank" %></p>
          <% end %>

        </div>
        <div class="revealed-answer">
          <p><%= sanitize @question.answer %></p>
          <div class="field text-left">
            <%= f.label :new_answer %><br>
            <%= f.text_area :new_answer, class: "form-control", rows: "5",
              value: "#{@question.answer}" %>
          </div>
        </div>
      </div>
      <div class="actions">
        <%= f.submit "Edit Answer", class: "primary-button" %>
        <%= link_to 'Back', question_path(@question), class: "btn btn-default pull-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/edit_question.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= form_for(@question) do |f| %>
      <%= hidden_field_tag :edit_type, "question" %>
      <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@question.errors.count, "error") %>
            prohibited this question from being edited:
          </h2>

          <ul>
            <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h1 class="page-header">
        Edit Question
      </h1>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title">Question <%= @question.number %></h2>
        </div>
        <div class="question-body">
          <p><%= sanitize @question.question_text %></p>
          <% if not(@question.external_link.blank?) %>
            <p><%= link_to "Click for additional information",
                           url_with_protocol(@question.external_link),
                           target: "_blank" %></p>
          <% end %>
          <div class="field">
            <%= f.label :new_text %><br>
            <%= f.text_area :new_text, class: "form-control", rows: "5",
              value: "#{@question.question_text}" %>
          </div>

        </div>
        <div class="revealed-answer">
          <p><%= sanitize current_answer(@question) %></p>
          <% if @question.answer_edited_at %>
            <p>
              <strong>Original Answer:</strong>
              <%= sanitize @question.answer %>
            </p>
          <% end %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit "Edit Question", class: "primary-button" %>
        <%= link_to 'Back', question_path(@question), class: "btn btn-default pull-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h1 class="page-header">
      <%= @quiz.subject %>
      <small> by <%= @quiz.author.name %></small>
    </h1>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">Question <%= @question.number %></h2>
      </div>
      <div class="question-body">
        <p><%= sanitize current_question_text(@question) %></p>
        <% if @question.question_edited_at %>
          <p>
            <strong>Original question:</strong>
            <%= sanitize @question.question_text %>
          </p>
        <% elsif @can_edit %>
          <p>
            <%= link_to "Edit this question", edit_question_question_path %>
          </p>
        <% end %>

        <% if not(@question.external_link.blank?) %>
          <p><%= link_to "Click for additional information",
                         url_with_protocol(@question.external_link),
                         target: "_blank" %></p>
        <% end %>
        <% if @response_sheet %>
          <% response = @question.responses.
                      find_by_response_sheet_id(@response_sheet) %>
          <strong>Your answer:</strong><br />
          <strong><%= response.response_text %></strong>
          <% if response.money %>
            <small>(Money)</small>
          <% end %>
        <% end %>
      </div>
      <div class="revealed-answer">
        <p><%= sanitize current_answer(@question) %></p>
        <% if @question.answer_edited_at %>
          <p>
            <strong>Original Answer:</strong>
            <%= sanitize @question.answer %>
          </p>
        <% elsif @can_edit %>
          <p>
            <%= link_to "Edit this answer", edit_answer_question_path %>
          </p>
        <% end %>
        </p>
      </div>
    </div>

    <% if @responses_hash %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Response</th>
            <th class="text-center">Count</th>
            <th class="text-center">Correct?</th>
          </tr>
        </thead>

        <tbody>
          <% @responses_hash.each do |response, hash| %>
            <tr>
              <td>
                <%= response %>
              </td>
              <td class="text-center">
                <%= hash[:count] %>
              </td>
              <td class="text-center">
                <% if hash[:correct] == true %>
                  Correct
                <% elsif hash[:correct] == false %>
                  Incorrect
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <%= link_to 'Back', quiz_path(@quiz), class: "btn btn-default pull-right" %>
  </div>
</div>