config/routes.rb
Rails.application.routes.draw do

  get 'about', to: 'static_pages#about', as: 'about'

  post 'grading/start/:quiz_id', to: 'grading#start', as: 'start_grading'

  post 'grading/complete/:quiz_id', to: 'grading#complete',
       as: 'complete_grading'

  get 'grading/:quiz_id/:question_number', to: 'grading#question',
      as: 'question_grading'

  post 'grading/:quiz_id/:question_number', to: 'grading#save_grading'

  get 'grading/:quiz_id', to: 'grading#show', as: :grading

  resources :players

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :response_sheets, only: [:create]

  resources :responses

  resources :questions, only: [:show, :update] do
    member do
      get "edit_question"
      get "edit_answer"
    end
  end

  resources :quizzes

  post 'start_quiz/:id', to: 'quizzes#start_quiz', as: 'start_quiz'
  get 'finalize/:id', to: 'quizzes#finalize', as: 'finalize'

  root 'quizzes#home_page'

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy, :finalize,
                                  :start_quiz]
  before_action :authenticate_user!, only: [:new, :create]
  before_action :authorize!, only: [:edit, :update, :destroy, :finalize,
                                    :start_quiz]
  before_action :check_unready!, only: [:finalize, :start_quiz]

  # GET /quizzes
  def index

    if params[:search]
      @quizzes = Quiz.title_search(params[:search]).
                      includes(:author, :champions).
                      paginate(page: params[:page], per_page: 50).
                      order(opening_date_time: :desc)
    else
      @quizzes = Quiz.active.includes(:author, :champions).
                      paginate(page: params[:page], per_page: 50).
                      order(opening_date_time: :desc)
    end

    @current_player = current_user.player if user_signed_in?
  end

  def home_page
    @current_player = current_user.player if user_signed_in?

    @playable_quizzes = Quiz.
      playable.
      includes(:author).
      where("approximate_grading_date_time > ?", 1.week.ago ).
      order(approximate_grading_date_time: :asc)
    @quizzes_being_graded = Quiz.being_graded.
                                 includes(:author).
                                 order(opening_date_time: :asc)
    if Quiz.complete.where('closing_date_time > ?', 1.week.ago).size > 10

      @complete_quizzes = Quiz.complete.
                               includes(:author, :response_sheets, :champions).
                               where('closing_date_time > ?', 1.week.ago).
                               order(closing_date_time: :desc)
    else
      @complete_quizzes = Quiz.complete.
                               includes(:author, :response_sheets, :champions).
                               order(closing_date_time: :desc).
                               limit(10)
    end
  end

  # GET /quizzes/1
  def show
    @response_sheet = nil
    @show_results = nil
    if not(@quiz.opened)
      authenticate_user!
      authorize!
    elsif (@quiz.complete)
      @show_results = true
      if user_signed_in?
        @response_sheet = @quiz.response_sheets.
                                includes(:player, responses: [:question]).
                                find_by player: current_user.player
      end
    elsif(@quiz.playable?)
      if not(@can_edit)
        # authenticate_user!
        if user_signed_in?
          @response_sheet = @quiz.response_sheets.find_or_initialize_by(
            player: current_user.player
            )
          @disabled = false
        else
          @response_sheet = @quiz.response_sheets.new
          @disabled = true
        end
        if @response_sheet.new_record?
          @response_sheet.create_responses
        end
      end
    elsif @quiz.being_graded?
      if @can_edit
        redirect_to grading_path(@quiz)
      else
        if user_signed_in?
          @response_sheet = @quiz.response_sheets.
                                  includes(:player, responses: [:question]).
                                  find_by(player: current_user.player)
        end
      end
    end
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    @quiz.set_defaults
  end

  # GET /quizzes/1/edit
  def edit

  end

  # POST /quizzes
  def create
    @quiz = current_user.player.authored_quizzes.new(quiz_params)
    if @quiz.save
      redirect_to @quiz, notice: 'Quiz was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /quizzes/1
  def update
    if @quiz.update(quiz_params)
      redirect_to @quiz, notice: 'Quiz was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /quizzes/1
  def destroy
    @quiz.destroy
    redirect_to quizzes_path, notice: 'Quiz was successfully destroyed.'
  end

  # GET finalize/1
  def finalize
    if @quiz.invalid?(:finalize)
      render 'edit'
    end
  end

  # POST start_quiz/1
  def start_quiz
    if @quiz.invalid?(:finalize)
      return render 'edit'
    end

    agdt = params[:quiz][:approximate_grading_date_time]

    if agdt < 8.hours.from_now
      return redirect_to finalize_path(@quiz),
          alert: "Quizzes must be open for at least eight hours."
    end


    if @quiz.start_quiz(agdt)
      # NoticeMailer.new_quiz(@quiz).deliver_later
      NewQuizWorker.perform_async(@quiz.id)
      redirect_to root_path, notice: "Your quiz is now live!"
    else
      render 'finalize', alert: "There was a problem starting your quiz."
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quiz
    @quiz = Quiz.includes(:author, :questions).order('questions.number').find(params[:id])
    @can_edit = user_signed_in? && current_user.player == @quiz.author
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def quiz_params
    params.require(:quiz).permit(:subject, :base_score,
                                 :money_question_count, :description,
                                 questions_attributes: [:id, :number,
                                                        :question_text,
                                                        :external_link,
                                                        :answer,
                                                        :grading_notes,
                                                        :_destroy])
  end

  # If a user is not authorized, redirect to the root
  def authorize!
    if not(@can_edit)
      redirect_to root_path,
                alert: "You are not authorized to view or edit this quiz."
    end
  end

  # If a quiz is already opened, redirect to quiz.
  def check_unready!
    if @quiz.opened
      redirect_to @quiz, alert: "This quiz has already been started."
    end
  end


end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz, html: {autocomplete: "off"}) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@quiz.errors.count, "error") %>
        prohibited this quiz from being saved:
      </h2>

      <ul>
        <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="field">
        <%= f.label :subject %><br>
        <%= f.text_field :subject, class: "form-control",
              placeholder: "The subject will also be the quiz's title"%>
      </div>
      <div class="field">
        <%= f.label :base_score %><br>
        <%= f.number_field :base_score, class: "form-control" %>
        <p class="help-block">
          The score given for a correct answer, outside of any bonuses from
          "money" questions. The default is 15.
        </p>
      </div>
      <div class="field">
        <%= f.label :money_question_count %><br>
        <%= f.number_field :money_question_count, class: "form-control" %>
        <p class="help-block">
          The number of questions in the quiz that players will "money,"
          receiving bonus points if they answer correctly. The default is 40% of the total questions.
        </p>
      </div>
      <div class="field">
        <%= f.label :description, class: "control-label" %><br>
        <%= f.text_area :description, rows: "5", class: "form-control",
              placeholder: "Add a short description that will introduce "\
                           "players to your quiz."%>
      </div>
      <p>
        Fill in the question information below. You don't need to have all of
        the questions filled in yet, but you can't start your quiz until
        every question has something for the question and the answer.
      </p>
      <p>
        To change the order of questions, use the arrow buttons to move a
        question forward or back.
      </p>
      <p>
        If one of your questions involves information like a video or image
        stored on another site, put the full URL of the page you wish to link
        to in the "External Link" field for that question. Be sure to include
        the "http://" prefix at the beginning, or the link may not work
        correctly. Please take care to insure that there are no unintended
        clues in the name of the URL or on the destination page.
      </p>
      <p>
        When you grade your quiz, the capitalization of player responses will
        change, and square brackets will be replaced with parentheses.
      </p>
    </div>
  </div>
  <div class="row" id="form-questions-row">
    <%= f.fields_for :questions,
      @quiz.questions do |questions_form| %>
      <div class="quiz-form-question-column
        col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-0
        col-md-4 col-md-offset-0 col-lg-3 col-lg-offset-0
        <%= 'hidden' if questions_form.object.number.blank? %>"
        data-id="<%=questions_form.index%>">

        <div class="panel panel-info">
          <div class="field panel-heading text-center" style="line-height:2em;">
            <button type="button" aria-label="Move Back"
              class="move-back btn btn-default pull-left"
              data-id="<%=questions_form.index%>">
              <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            </button>
            Question
            <span class="movable-question-number-text">
              <%= questions_form.object.number %>
            </span>
            <button type="button" aria-label="Move Forward"
              class="move-forward btn btn-default pull-right"
              data-id="<%=questions_form.index%>">

              <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
            </button>
            <%= questions_form.hidden_field :number, class: "movable-question-number-value" %>
            <%= questions_form.hidden_field :id %>
          </div>
          <div class="panel-body">
            <div class="field">
              <%= questions_form.label :question_text %><br>
              <%= questions_form.text_area :question_text, class: "form-control",
                    rows: "5", placeholder: "Enter the text of the question" %>
            </div>
            <div class="field">
              <%= questions_form.label :answer %><br>
              <%= questions_form.text_field :answer, class: "form-control",
                    placeholder: "Enter the text of the question" %>
            </div>
            <div class="field">
              <%= questions_form.label :external_link %><br>
              <%= questions_form.text_field :external_link,
                    class: "form-control",
                    placeholder: "e.g., http://alpacafarmtrivia.com" %>
            </div>
            <div class="field">
              <%= questions_form.label :grading_notes %><br>
              <%= questions_form.text_area :grading_notes,
                    class: "form-control", rows: "4",
                    placeholder: "Enter any notes that will help you during "\
                                  "grading (alternate answers, answers that "\
                                  "won't be accepted, etc.)" %>
            </div>
          </div>
          <div class="panel-footer text-right">
            <%= questions_form.hidden_field :_destroy, value: questions_form.object.number.blank? %>
            <button type="button"
              class="delete-question btn btn-default"
              data-id="<%=questions_form.index%>">
              Delete Question
            </button>
          </div>
        </div>
      </div>
      <% unless questions_form.object.number.blank? %>
        <p class="form-question-clearfix"></p>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <p class="col-xs-8 col-xs-offset-2 text-center">
      <button type="button" class="btn btn-primary add-new-question ">
        Add New Question
      </button>
    </p>
  </div>

  <div class="row">
    <div class="actions">
      <%= f.submit 'Save and Preview', class: "primary-button" %>
      <%= link_to 'Back', quizzes_path, class: "btn btn-default pull-right" %>
    </div>
  </div>
<% end %>

app/views/quizzes/_in_progress.html.erb
<div class="alert alert-warning">
  <p><strong>Your quiz is still in progress.</strong>
    There have been
    <%= @quiz.response_sheets.size %> participants so far. You set the
    approximate grading time as
    <strong><%= localize_agdt @quiz.approximate_grading_date_time,
                              :basic %></strong>,
    which means
    <% if Time.now > @quiz.approximate_grading_date_time %>
      this quiz is ready for grading.
    <% else %>
      you still have
      <%= distance_of_time_in_words_to_now(@quiz.approximate_grading_date_time) %>
      until you can begin grading.
    <% end %>
  </p>
  <% if Time.now > @quiz.approximate_grading_date_time %>
    <p>
      <%= link_to "Close Quiz & Start Grading", start_grading_path(@quiz),
            method: :post,
            class: "btn btn-primary center-block",
            confirm: "Are you sure you want to close this quiz for grading?"%>
    </p>
  <% end %>
</div>

app/views/quizzes/_introduction.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h1 class="page-header">
      <%= @quiz.subject %>
      <small> by <%= @quiz.author.name %></small>
    </h1>

    <% if @quiz.description %>
      <h2>Description</h2>
      <p class="text-justify"><%= sanitize @quiz.description %></p>
      <hr>
    <% end %>

    <h2>Instructions</h2>
    <p class="text-justify">
      Answer the questions below to the best of your ability <em>without
      using outside resources</em>. Outside references include (but certainly
      are not limited to) searching for an answer on the internet, looking at
      maps, using a calculator, or asking a friend (or foe) if they know the
      answer. Basically, you are relying on your brain (and maybe a pencil
      and paper).
    </p>

    <p class="text-justify">
      For each correct answer, you will receive
      <strong><%= @quiz.base_score %></strong>
      points. You must also mark
      <strong><%= @quiz.money_question_count %></strong>
      questions as "money" questions. For each money question that you answer
      correctly, you will receive bonus points equal to the percent of players
      who answered <em>incorrectly</em>. (That is, if 25% of players got a
      question right, its money bonus would be worth 75 points.) You still
      don't get any points for a wrong answer, though, so try to select the
      hardest questions you think you have answered correctly. (Note: You
      can't use outside resources to help pick your money questions either.)
    </p>

    <% if @quiz.being_graded? %>
      <p class="text-justify">
        This quiz is closed for grading, and you can no longer submit answers.
        When the author has finished grading, the results will be published on
        this page.
    </p>
    <% elsif @can_edit && @quiz.playable? %>
      <%= render 'in_progress' %>
    <% elsif @disabled %>
      <div class="alert alert-warning">
        <p><strong>
          Only logged-in users can participate in a quiz.
          <%= link_to "Log In", new_user_session_path %>
          or
          <%= link_to "Sign Up", new_user_registration_path %>
          now to play. </strong></p>
      </div>
    <% else %>
      <p>
        You can submit your answers until grading begins.
        <%= @quiz.author.name %> currently plans to begin grading around
        <strong><%= localize_agdt @quiz.approximate_grading_date_time, :basic %></strong>.
      </p>
      <br />
    <% end %>
  </div>
</div>

app/views/quizzes/_response_form.html.erb
<%= form_for(@response_sheet, html: {autocomplete: "off"} ) do |rs| %>
  <%= rs.hidden_field :quiz_id, value: @response_sheet.quiz.id %>
  <div class="row row-full-height">
    <% if @response_sheet.errors.any? %>
      <div id="error_explanation">
        <strong>There were some problems with your reponse:</strong>
        <ul>
          <% @response_sheet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h2>Questions</h2>

    <% @response_sheet.responses.
         sort { |a, b| a.question.number <=> b.question.number }.
         each do |response| %>
      <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-0
                  col-md-4 col-md-offset-0 col-lg-3 col-lg-offset-0
                  col-full-height">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title">Question <%= response.question.number %></h2>
          </div>
          <div class="question-body">
            <p><%= sanitize current_question_text(response.question) %></p>
            <% if not(response.question.external_link.blank?) %>
              <p><%= link_to "Click for additional information",
                       url_with_protocol(response.question.external_link),
                       target: "_blank" %></p>
            <% end %>

            <%= rs.fields_for :responses, response do |r| %>
              <%= r.hidden_field :question_id, value: response.question.id %>
              <div class="field">
                <%= r.label :response_text, "Your answer:",
                            class: "form-label" %><br>
                <%= r.text_field :response_text, class: "form-control",
                                 disabled: @disabled %>
              </div>
              <div class="field text-right">
                <%= r.label :money, "Money?", class: "checkbox-inline" %>
                <%= r.check_box :money, class: "checkbox-inline",
                                disabled: @disabled %>
              </div>

            <% end %>
          </div>
        </div>
      </div>
      <div class="question-clearfix"></div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 col-sm-12 col-sm-offset-0">
      <div class="actions">
        <%= rs.submit "Submit your answers", class: "primary-button",
              disabled: @disabled,
              data: {confirm: "You are on your honor to complete this "\
                              "quiz on your own. By submitting your answers "\
                              "here, you affirm that you did not consult any "\
                              "outside resources while working on this quiz. "\
                              "(If you did, please don't submit your "\
                              "answers.)"} %>
        <%= link_to "Back", root_path, class: "btn btn-default pull-right"  %>

      </div>
    </div>
  </div>

<% end %>

app/views/quizzes/_results.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h1 class="page-header">
      <%= @quiz.subject %>
      <small> by <%= @quiz.author.name %></small>
    </h1>

    <h2>Champion(s):</h2>
    <% @quiz.response_sheets.champions.each do |rs| %>
      <h3 class="text-right">
        <%= rs.player.name %><br />
        <small><%= rs.player.motto %></small>
      </h3>
    <% end %>

    <hr>

    <h2 class="h3">Runner(s)-Up:</h2>
    <% @quiz.response_sheets.runners_up.each do |rs| %>
      <h3 class="h4 text-right">
        <%= rs.player.name %><br />
        <small><%= rs.player.motto %></small>
      </h3>
    <% end %>
    <hr>
    <% if @response_sheet %>
      <h2>Your Result</h2>
      <h3>
        <%= @response_sheet.rank.ordinalize %> Place!
        <small>
          <%= @response_sheet.percentile_rank.to_i.ordinalize %>
          percentile rank
        </small>
      </h3>
      <h4>
        Score:
        <%= @response_sheet.score %> points
        <small>out of a possible <%= @quiz.maximum_score %></small>
      </h4>
      <hr>
    <% end %>

    <% unless @quiz.blank? %>
      <h2>Quiz Description</h2>
      <p class="text-justify"><%= sanitize @quiz.description %></p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-md-9">
    <h2>Full Results:</h2>
    <div class="table-responsive">
      <table class="table table_striped table-hover
                    table-condensed table-bordered">
        <thead>
          <tr>
            <th class="text-center">Rank</th>
            <th>Player</th>
            <th class="text-center">Total</th>
            <th class="text-center">%ile</th>
            <% @quiz.questions.each do |q| %>
              <th class="text-center"><%= q.number %></th>
            <% end %>
          </tr>
        </thead>

        <tr>
          <th colspan="2" class="text-right">Money Value (% Incorrect):</th>
          <th></th>
          <th></th>
          <% @quiz.questions.each do |q| %>
            <th class="text-center">
              <%= q.money_value.to_s.rjust(2, '0') %>
            </th>
          <% end %>
        </tr>


        <tbody>
          <% @quiz.response_sheets.includes(:player, responses: :question).
                   order(:rank, 'questions.number').
                   each do |rs| %>
            <tr>
              <td class="text-center"><%= rs.rank %></td>
              <td><%= rs.player.name %></td>
              <td class="text-center"><%= rs.score %></td>
              <td class="text-center">
                <%= [1, rs.percentile_rank.floor].max %>
              </td>

              <% rs.responses.each do |r| %>
                <td class="text-center <%= result_color(r) %>">
                  <%= r.correct ? @quiz.base_score.to_s.rjust(2, '0') : "00" %><br />
                  <% if r.money %>
                    <%= r.correct ? r.question.money_value.to_s.rjust(2, '0') : "00" %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-xs-12
              col-sm-8 col-sm-offset-2
              col-md-3 col-md-offset-0">
    <h2>Questions:</h2>
    <% @quiz.questions.order(:number).each do |question| %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= link_to "Question #{question.number}",
                        question_path(question) %>
          </h3>
        </div>
        <div class="question-body">
          <p><%= sanitize current_question_text(question) %></p>
          <% if not(question.external_link.blank?) %>
            <p><%= link_to "Click for additional information",
                           url_with_protocol(question.external_link),
                           target: "_blank" %></p>
          <% end %>
        </div>
        <% if @response_sheet %>
          <% response = question.responses.
                        find_by_response_sheet_id(@response_sheet) %>
          <ul class="list-group">
            <li class="list-group-item">
              <p class="text-left">
                <strong>Your response:</strong>
              </p>
              <p class="text-center">
                <strong class="text-center"><%= response.response_text %></strong>
                <% if response.money %>
                  <span class='glyphicon glyphicon-usd' aria-hidden='true'></span>
                  <span class="sr-only">Moneyed</span>
                <% end %>
              </p>
            </li>
          </ul>
        <% end %>
        <%= content_tag(:div, "Click to Reveal Answer",
                        {class: "click-to-reveal-answer",
                        "question-number" => question.id}
                        ) %>
        <%= content_tag(:div, current_answer(question),
                        {class: "concealed-answer",
                        "question-number" => question.id}
                        ) %>
      </div>
    <% end %>
  </div>
</div>

app/views/quizzes/_review.html.erb
<div class="row row-full-height">
  <h2>Questions</h2>
  <%= render @quiz.questions %>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2 col-sm-12 col-sm-offset-0">
    <% if not(@quiz.opened) && current_user.player == @quiz.author %>
    <div class="btn-group pull-left" role="group">
      <%= link_to 'Edit', edit_quiz_path(@quiz), class: "primary-button" %>
      <%= link_to 'Finalize', finalize_path(@quiz), class: "btn btn-info" %>
    </div>
    <% end %>
    <%= link_to 'Back', root_path, class: "btn btn-default pull-right" %>
  </div>
</div>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

app/views/quizzes/finalize.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h1 class="page-header">Start Your Quiz</h1>
    <p>
      Before you start your quiz, you'll need to set a time when you expect
      to begin grading the answers. You don't have to begin grading at exactly
      the time you set, but you can't start until the time has passed. This
      will let players know how long they have to participate in the quiz.
    </p>
    
    <p>
      Take a moment to review all of your questions and answers. Once you've
      started your quiz, you won't be able to change anything.
    </p>
    <%= form_for(@quiz, url: start_quiz_path(@quiz),
                        html: {method: "post"}) do |f| %>
      <div class="field">
        <%= f.label :approximate_grading_date_time, class: "form-label" %>
        <%= f.datetime_local_field :approximate_grading_date_time,
               value: DateTime.current.tomorrow.strftime("%Y-%m-%dT%T"),
               min: DateTime.current.advance(hours: 8).strftime("%Y-%m-%dT%T"),
               max: DateTime.current.advance(days: 7).strftime("%Y-%m-%dT%T"),
               class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Start Your Quiz", class: "primary-button" %>
        <%= link_to "Back", @quiz, class: "btn btn-default pull-right" %>
      </div>
    <% end %>
  </div>
</div>
  
  <%= render 'introduction' %>
  <%= render @quiz.questions.order(:number) %>

app/views/quizzes/home_page.html.erb
<div class="page-header">
  <h1>Welcome to the Alpaca Farm!</h1>
</div>

<div class="row">
  <div class="col-xs-12 col-xs-offset-0
              col-sm-8 col-sm-offset-2">
    <h2>Playable Quizzes</h2>

    <table class="table table_striped table-hover">
      <thead>
        <tr>
          <th colspan="2" class="text-center">Subject</th>
          <th>Author</th>
          <th>Deadline</th>
        </tr>
      </thead>

      <tbody>
      <% @playable_quizzes.each do |quiz| %>
        <tr>
          <td class="text-center"><%= play_button(quiz) %></td>
          <td class="text-center"><%= link_to quiz.subject, quiz %></td>
          <td><%= link_to quiz.author.name, player_path(quiz.author) %></td>
          <td><%= l quiz.approximate_grading_date_time, format: :basic %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
    <hr>
    <h2>Site News</h2>
    <p>
      Quizzes can now hold a variable number of questions, as few as five, and as many as twenty-five. When creating or editing a quiz, use the new buttons to organize your quiz, and let me know if there are any problems.
    </p>
    <hr>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-xs-offset-0
              col-sm-8  col-sm-offset-2">

    <h2>Recently Completed Quizzes</h2>

    <table class="table table_striped table-hover">
      <thead>
        <tr>
          <th>Subject</th>
          <th>Author</th>
          <th class="text-center">Participants</th>
          <th class="text-right">Champion(s)</th>
        </tr>
      </thead>

    <tbody>
      <% @complete_quizzes.each do |quiz| %>
        <tr>
          <td><%= link_to quiz.subject, quiz %></td>
          <td><%= link_to quiz.author.name, player_path(quiz.author) %></td>
          <td class="text-center"><%= quiz.response_sheets_count %></td>
          <td class="text-right">
            <% quiz.champions.each do |c| %>
            <%= link_to c.player.name, c.player %><br />
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

    <% if @quizzes_being_graded %>
    <h3>
      There
      <%= @quizzes_being_graded.size == 1 ? 'is' : 'are' %>
      <%= pluralize @quizzes_being_graded.size, 'quiz' %>
      currently being graded.
    </h3>
  <% end %>

  <%= link_to 'Create a new quiz', new_quiz_path, class: "primary-button" %>
  <%= link_to 'See all quizzes', quizzes_path, class: "btn btn-default pull-right" %>

  </div>
  <br>
</div>

app/views/quizzes/index.html.erb
<div class="page-header">
  <%= form_tag(quizzes_path, method: "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-group pull-right">
      <%= search_field_tag :search, params[:search], class: "form-control", placeholder: "Search quizzes" %>
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">
          <span class='glyphicon glyphicon-search' aria-hidden='true'></span>
        </button>
      </span>
    </div>
  <% end %>
  <h1>Quizzes</h1>
</div>

<table class="table table_striped table-hover">
  <thead>
    <tr>
      <th colspan="2" class="text-center">Subject</th>
      <th>Author</th>
      <th class="text-center">Status</th>
      <th class="text-center">Deadline / Closed</th>
      <th class="text-center">Participants</th>
      <th class="text-right">Champion(s)</th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td class="text-center"><%= play_button(quiz) %></td>
        <td class="text-center"><%= link_to quiz.subject, quiz %></td>
        <td><%= link_to quiz.author.name, player_path(quiz.author) %></td>
        <td class="text-center"><%= quiz_status(quiz).titleize %>
        <td class="text-center"><%= l index_time(quiz), format: :basic %></td>
        <td class="text-center"><%= quiz.response_sheets_count %></td>
        <td class="text-right">
          <% quiz.champions.each do |c| %>
            <%= link_to c.player.name, c.player %><br />
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @quizzes, renderer: BootstrapPagination::Rails %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form' %>

app/views/quizzes/show.html.erb
<% if @show_results %>
  <%= render 'quizzes/results' %>
<% else %>
  <%= render 'quizzes/introduction' %>
  <% if @quiz.playable? && not(@can_edit) && @response_sheet.new_record? %>
    <%= render 'quizzes/response_form' %>
  <% else %>
    <%= render 'quizzes/review' %>
  <% end %>
<% end %>