config/routes.rb
Rails.application.routes.draw do

  get 'about', to: 'static_pages#about', as: 'about'

  post 'grading/start/:quiz_id', to: 'grading#start', as: 'start_grading'

  post 'grading/complete/:quiz_id', to: 'grading#complete',
       as: 'complete_grading'

  get 'grading/:quiz_id/:question_number', to: 'grading#question',
      as: 'question_grading'

  post 'grading/:quiz_id/:question_number', to: 'grading#save_grading'

  get 'grading/:quiz_id', to: 'grading#show', as: :grading

  resources :players

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :response_sheets, only: [:create]

  resources :responses

  resources :questions, only: [:show, :update] do
    member do
      get "edit_question"
      get "edit_answer"
    end
  end

  resources :quizzes

  post 'start_quiz/:id', to: 'quizzes#start_quiz', as: 'start_quiz'
  get 'finalize/:id', to: 'quizzes#finalize', as: 'finalize'

  root 'quizzes#home_page'

end

app/views/shared/_flash_display.html.erb
<% if notice %>
  <div class="alert alert-success" style="margin: 0px">
    <div class="container">
      <span id="notice"><%= notice %></span>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger" style="margin: 0px">
    <div class="container">
      <span id="alert"><%= alert %></span>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">
      Created by Tablesaw Tablesawsen
      <span class="pull-right">
        Contact:
        <%= mail_to "contact@alpacafarmtrivia.com" %>
      </span>
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#collapsibleMenu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpaca Farm (beta)", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse navbar-right" id="collapsibleMenu">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li> 
        <li><%= link_to "Quizzes", quizzes_path %></li> 
        <li><%= link_to "Create a Quiz", new_quiz_path %></li> 
        <li><%= link_to "Players", players_path %></li>
        <%= render 'devise/menu/registration_items' %>
        <%= render 'devise/menu/login_items' %>
      </ul>
    </div>
  </div>
</div>