config/routes.rb
Rails.application.routes.draw do

  get 'about', to: 'static_pages#about', as: 'about'

  post 'grading/start/:quiz_id', to: 'grading#start', as: 'start_grading'

  post 'grading/complete/:quiz_id', to: 'grading#complete',
       as: 'complete_grading'

  get 'grading/:quiz_id/:question_number', to: 'grading#question',
      as: 'question_grading'

  post 'grading/:quiz_id/:question_number', to: 'grading#save_grading'

  get 'grading/:quiz_id', to: 'grading#show', as: :grading

  resources :players

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :response_sheets, only: [:create]

  resources :responses

  resources :questions, only: [:show, :update] do
    member do
      get "edit_question"
      get "edit_answer"
    end
  end

  resources :quizzes

  post 'start_quiz/:id', to: 'quizzes#start_quiz', as: 'start_quiz'
  get 'finalize/:id', to: 'quizzes#finalize', as: 'finalize'

  root 'quizzes#home_page'

end

app/models/player.rb
class Player < ActiveRecord::Base
  store_accessor :notifications, :new_quiz
  store_accessor :notifications, :graded_quiz


  #ActiveRecord associations
  belongs_to :user
  has_many :authored_quizzes, class_name: "Quiz",
                              foreign_key: "author_id"
  has_many :participated_quizzes, class_name: "Quiz",
                                  source: :quiz,
                                  through: :response_sheets,
                                  foreign_key: "quiz_id"
  has_many :response_sheets
  has_many :notices

  # Default validations
  validates :name, presence: true, uniqueness: {case_sensitive: false},
            length: {in: 3..20},
            format: {with: /\A[a-zA-Z0-9-]+\Z/,
                     message: "only allows letters, numbers, and hyphens (-)"}

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update]
  before_action :authorize!, only: [:edit, :update]

  # GET /players
  def index
    @players = Player.paginate(page: params[:page], per_page: 50).
                      order(:name)
  end

  # GET /players/1
  def show
      @authored_quizzes = @player.authored_quizzes.includes(:champions).order(opening_date_time: :desc)
      @response_sheets = @player.response_sheets.includes(quiz: :author).
                                 paginate(page: params[:page], per_page: 50).
                                 order(created_at: :desc)
  end

  # GET /players/1/edit
  def edit
    nil_to_string(:new_quiz, :graded_quiz)
  end

  # PATCH/PUT /players/1
  def update
    params_to_nil("new_quiz", "graded_quiz")

    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
    @can_update = user_signed_in? && current_user.player == @player
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def player_params
    params.require(:player).permit(:location, :motto, :time_zone, :new_quiz, :graded_quiz)
  end

  # If a user is not authorized, redirect to showing the player template
  def authorize!
    if not(@can_update)
      redirect_to player_path(@player),
        alert: "You are not authorized to edit this profile."
    end
  end

  # Change the string "nil" to nil value in params that will be saved in hstore
  def params_to_nil (*whitelist_keys)
    hstore_hash = params["player"].select do |key, value|
      whitelist_keys.include? key
    end
    if hstore_hash.has_value? "nil"
      hstore_hash.each do |key, value|
        params["player"][key] = nil if value == "nil"
      end
    end
  end

  # Change nil values in notifications to the sting "nil" for handling in HTML
  def nil_to_string (*attributes)
    attributes.each do |attribute|
      if @player.send(attribute) == nil
        @player.send(attribute.to_s + "=", "nil")
      end
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <strong><%= pluralize(@player.errors.count, "error") %> prevented
                  this profile from being saved:</strong>

      <ul>
        <% @player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_zone, class: "control-label" %>
    <%= f.time_zone_select :time_zone,
                            ActiveSupport::TimeZone.us_zones, {},
                            {class: "form-control"} %>
  </div>

  <div class="field">
    <%= f.label :location, class: "control-label" %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :motto, class: "control-label" %>
    <%= f.text_field :motto, class: "form-control" %>
  </div>

  <h3>Email address and password</h3>
  <%= link_to "Click here to update your email address or password",
              edit_user_registration_path %>

  <h3>Email notification settings</h3>

  <div class="field">
    <h4>Notify me when new quizzes go live:</h4>
    <%= f.radio_button :new_quiz, "daily" %>
    <%= f.label "new_quiz_daily", "Once per day" %></br>
    <%= f.radio_button :new_quiz, "immediately" %>
    <%= f.label "new_quiz_immediately", "Immediately" %></br>
    <%= f.radio_button :new_quiz, "nil" %>
    <%= f.label "new_quiz_nil", "Never" %>
  </div>

  <div class="field">
    <h4>Notify me when a quiz I participate in has been graded</h4>
    <%= f.radio_button :graded_quiz, "daily" %>
    <%= f.label "graded_quiz_daily", "Once per day" %></br>
    <%= f.radio_button :graded_quiz, "immediately" %>
    <%= f.label "graded_quiz_immediately", "Immediately" %></br>
    <%= f.radio_button :graded_quiz, "nil" %>
    <%= f.label "graded_quiz_nil", "Never" %>
  </div>


<div class="actions">
    <%= f.submit "Update", class: "primary-button" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class = "row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="page-header">
      <h1>Edit Profile</h1>
    </div>

    <%= render 'form' %>

    <%= link_to 'Cancel', player_path(@player),
                class: "btn btn-default pull-right" %>
  </div>
</div>

app/views/players/index.html.erb
<div class="page-header">
  <h1>Players</h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="text-left">Name</th>
      <th class="text-center">Location</th>
      <th class="text-center">Played</th>
      <th class="text-center">Authored</th>
      <th class="text-right">Joined</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td class="text-left"><%= link_to player.name, player %></td>
        <td class="text-center"><%= player.location %></td>
        <td class="text-center"><%= player.response_sheets_count || 0 %></td>
        <td class="text-center"><%= player.opened_quizzes_count || 0 %></td>
        <td class="text-right"><%= l player.created_at, format: :date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @players, renderer: BootstrapPagination::Rails %>
<br>
<%= link_to 'Become an Alpaca', new_user_registration_path %>

app/views/players/show.html.erb
<div class="page-header">
  <h1>
    <%= @player.name %>
    <small><%= @player.motto %></small>
  </h1>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-0" >
    <h2>Profile</h2>
    <p>
      <strong>Location:</strong>
      <%= @player.location %>
    </p>

    <% if @can_update %>
      <%= link_to 'Edit Profile', edit_player_path(@player),
                  class: "btn btn-default pull-right"%>
    <% end %>
  </div>

  <div class="col-xs-12 col-md-6">
    <% if @can_update %>
      <h2>Quizzes Under Construction</h2>
      <% if @player.authored_quizzes.unready.empty? %>
        <p class="text-center">
          <em>You have no quizzes under construction.</em>
        </p>
      <% else %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Subject</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @authored_quizzes.unready.each do |quiz| %>
              <tr>
                <td><%= link_to quiz.subject, edit_quiz_path(quiz) %></td>
                <td class="text-right">
                  <%= link_to "Edit", edit_quiz_path(quiz),
                              class: "btn btn-default" %>
                  <%= link_to "Finalize", finalize_path(quiz),
                              class: "btn btn-default" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h2>Authored</h2>
    <% if @authored_quizzes.active.empty? %>
      <p class="text-center">
        <em>
          <% if @can_edit %>
            You have
          <% else %>
            <%= @player.name %> has
          <% end %>
          not yet authored a quiz.
        </em>
      </p>
    <% else %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Subject</th>
            <th class="text-center">Players</th>
            <th>Started</th>
            <th>Status</th>
            <th>Champion(s)</th>
          </tr>
        </thead>

        <tbody>
          <% @authored_quizzes.active.each do |quiz| %>
            <tr>
              <td><%= link_to quiz.subject, quiz %></td>
              <td class="text-center"><%= quiz.response_sheets_count %></td>
              <td><%= l quiz.opening_date_time, format: :date %></td>
              <td><%= quiz_status(quiz).titleize %></td>
              <td>
                <% quiz.champions.each do |champion| %>
                  <%= champion.player.name %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h2>Played</h2>
    <% if @response_sheets.empty? %>
      <p class="text-center">
        <em>
          <% if @can_edit %>
            You have
          <% else %>
            <%= @player.name %> has
          <% end %>
          not yet participated in a quiz.
        </em>
      </p>
    <% else %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Subject</th>
            <th>Started</th>
            <th class="text-center">Score</th>
            <th class="text-center">Percentile</th>
            <th class="text-center">Rank (of Total)</th>
            <th class="text-right">Author</th>
          </tr>
        </thead>

        <tbody>
          <% @response_sheets.each do |rs| %>
            <tr>
              <td><%= link_to rs.quiz.subject, rs.quiz %></td>
              <td><%= l rs.quiz.opening_date_time, format: :date %></td>
              <td class="text-center"><%= rs.score %></td>
              <td class="text-center">
                <%= number_with_precision(rs.percentile_rank, precision: 0) %>
              </td>
              <td class="text-center">
                <% if rs.rank %>
                  <%= rs.rank %> of
                  (<%= rs.quiz.response_sheets.size %>)
                <% end %>
              </td>
              <td class="text-right">
                <%= link_to rs.quiz.author.name, rs.quiz.author %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @response_sheets, renderer: BootstrapPagination::Rails %>

    <% end %>
  </div>
</div>

<%= link_to 'Back', players_path, class: "btn btn-primary pull-left" %>